import {StyleSheet} from 'react-native';
import {widthPercentage, heightPercentage, fontPercentage} from '/Responsive';
import { rotationHandlerName } from 'react-native-gesture-handler/lib/typescript/handlers/RotationGestureHandler';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f6f9',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    flexGrow: 1,
    height: '100%',
  },
  imageContainer: {
    flexGrow: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  center: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: heightPercentage(10),
  },
  views: {
    paddingTop: heightPercentage(40),
    flexGrow: 1,
  },
  playButtonContainer: {
    marginHorizontal: widthPercentage(50),
    borderWidth: 0.5,
    borderColor: '#bbb',
    borderRadius: 40,
  },
  seekbar: {
    width: '100%',
    paddingTop: heightPercentage(15),
    paddingBottom: heightPercentage(25),
    paddingHorizontal: widthPercentage(20),
    backgroundColor: 'white',
  },
  track: {
    height: 2,
    borderRadius: 1,
    backgroundColor: '#FFF',
  },
  thumb: {
    width: 2,
    height: 2,
    backgroundColor: '#3D425C',
  },
  chatContainer: {
    flexGrow: 1,
    paddingHorizontal: widthPercentage(20),
  },
  inprogress: {
    marginTop: -8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  descText: {
    includeFontPadding: false,
    color: '#555',
    fontSize: fontPercentage(30),
    fontWeight: 300,
    marginLeft: widthPercentage(5),
    paddingVertical: heightPercentage(5),
    paddingRight: widthPercentage(15),
  },
  timeText: {
    includeFontPadding: false,
    color: '#121212',
    fontSize: fontPercentage(60),
    fontWeight: 300,
    marginLeft: widthPercentage(5),
    paddingTop: heightPercentage(5),
    paddingRight: widthPercentage(15),
  },
  chatBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginRight: widthPercentage(10),
    marginTop: heightPercentage(25),
  },
  speech: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 13,
    borderTopLeftRadius: 0,
    paddingHorizontal: widthPercentage(12),
    paddingVertical: heightPercentage(10),
    marginRight: widthPercentage(10),
    marginTop: heightPercentage(8),
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: {
      width: 0,
      height: heightPercentage(1),
    },
    shadowRadius: 6,
    shadowOpacity: 1,
    elevation: 10,
  },
  row: {
    width: '100%',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  contents: {
    includeFontPadding: false,
    color: '#111',
    fontSize: fontPercentage(17),
    fontWeight: 500,
    marginRight: widthPercentage(5),
  },
  nameText: {
    includeFontPadding: false,
    color: '#111',
    fontSize: fontPercentage(18),
    fontWeight: 600,
    marginRight: widthPercentage(5),
  },
  timeStamp: {
    includeFontPadding: false,
    color: '#555',
    fontSize: fontPercentage(14),
    fontWeight: 300,
    marginLeft: widthPercentage(5),
    marginTop: heightPercentage(10),
  },
  buttonContainer: {
    backgroundColor: '#fff',
    paddingVertical: heightPercentage(30),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    marginHorizontal: widthPercentage(40),
    paddingHorizontal: widthPercentage(20),
    paddingVertical: widthPercentage(20),
    width: widthPercentage(340),
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 17,
  },
  modalImageContainer: {
    marginHorizontal: widthPercentage(20),
    marginVertical: widthPercentage(20),
    backgroundColor: '#EAEAEC', //'#f4f6f9',
    width: '100%',
    padding: widthPercentage(15),
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
  },
  scriptContainer: {
    marginHorizontal: widthPercentage(20),
    marginVertical: widthPercentage(20),
    backgroundColor: '#EAEAEC', //'#f4f6f9',
    width: '100%',
    height: heightPercentage(300),
    padding: widthPercentage(15),
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
  },
  contentImage: {
    width: widthPercentage(100),
    height: widthPercentage(100),
  },
  title: {
    textAlign: 'center',
    includeFontPadding: false,
    color: '#121212',
    fontSize: fontPercentage(22),
    fontWeight: 500,
    marginLeft: widthPercentage(5),
    paddingVertical: heightPercentage(10),
    paddingRight: widthPercentage(15),
  },
  text: {
    textAlign: 'center',
    includeFontPadding: false,
    color: '#555',
    fontSize: fontPercentage(16),
    fontWeight: 300,
    marginLeft: widthPercentage(5),
    paddingTop: heightPercentage(10),
    paddingRight: widthPercentage(15),
  },
  spaceB: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calcelButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '48%',
    paddingVertical: heightPercentage(17),
    paddingHorizontal: heightPercentage(50),
    marginTop: heightPercentage(25),
    backgroundColor: '#fff',
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#60AAEF',
  },
  calcelBtnText: {
    includeFontPadding: false,
    fontSize: fontPercentage(19),
    fontWeight: '700',
    color: '#60AAEF',
  },
  button: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '48%',
    paddingVertical: heightPercentage(17),
    paddingHorizontal: heightPercentage(50),
    marginTop: heightPercentage(25),
    backgroundColor: '#60AAEF',
    borderRadius: 7,
  },
  longButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingVertical: heightPercentage(17),
    paddingHorizontal: heightPercentage(50),
    marginTop: heightPercentage(25),
    backgroundColor: '#60AAEF',
    borderRadius: 7,
  },
  btnText: {
    includeFontPadding: false,
    fontSize: fontPercentage(19),
    fontWeight: '700',
    color: '#fff',
  },
  itemBox: {
    width: '100%',
    marginTop: heightPercentage(10),
    marginHorizontal: widthPercentage(20),
  },
  nameInputBox: {
    width: '100%',
    height: heightPercentage(50),
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dddddd',
    marginTop: heightPercentage(5),
    paddingLeft: widthPercentage(20),
    marginLeft: widthPercentage(0),
    color: '#121212',
    fontSize: fontPercentage(17),
  },
  playBox: {
    width: '100%',
    paddingHorizontal: widthPercentage(30),
    paddingVertical: heightPercentage(5), 
    borderRadius: 10,
    marginVertical: heightPercentage(3),
    backgroundColor: '#f2f3f9',
    flexDirection: 'column',
    alignItems: 'center',
  },
  profileImg: {
    width: widthPercentage(35),
    height: widthPercentage(35),
    borderRadius: 30,
    marginRight: widthPercentage(7),
  }
});

export default styles;
